# Documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/debricked
    id: cli
    binary: debricked
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.version={{.Version}}

archives:
    - name_template: >-
        {{ .ProjectName }}_
        {{- if eq .Os "darwin" }}macOS_
        {{- else }}{{ .Os }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc

nfpms:
  - maintainer: viktigpetterr <viktor.grasljunga@gmail.com>
    description: Debricked's own command line interface.
    homepage: https://github.com/debricked/cli
    license: MIT
    formats:
      - deb
      - rpm
      - apk
