jobs:
- job: debricked_scan
  displayName: Debricked scan
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: MavenAuthenticate@0
      displayName: 'Maven Authenticate'
      inputs:
        artifactsFeeds: <your-private-repository-id>
    - script: |
        curl -LsS https://github.com/debricked/cli/releases/download/release-v2/cli_linux_x86_64.tar.gz | tar -xz debricked
        ./debricked scan
      displayName: Debricked scan
      env:
        DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)
