stages:
  - build
  - scan

build:
  stage: build
  image: go
  script:
    - |
      printf "$(go mod graph)\n\n$(go list -mod=readonly -e -m all)" > .debricked-go-dependencies.txt
  artifacts:
    paths:
      - .debricked-go-dependencies.txt
    expire_in: 1 day

debricked:
  stage: scan
  image:
    name: debricked/cli
  script: debricked scan
  variables:
    DEBRICKED_TOKEN: $DEBRICKED_TOKEN
