name: Soot

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  soot-wrapper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'debricked/soot-wrapper'

      - name: Calculate checksum
        id: calc-checksum
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - name: Cache JARs
        uses: actions/cache@v2
        id: cache-jars
        with:
          path: |
            java/common/target/*.jar
          key: ${{ runner.os }}-soot-wrapper-${{ matrix.java-version }}-${{ steps.calc-checksum.outputs.hash }}

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd java/common/
          mvn clean package -X -DskipTests

      - name: Upload JAR if cache missed
        uses: actions/upload-artifact@v2
        with:
          name: soot-wrapper-${{ matrix.java-version }}.jar
          path: java/common/target/*.jar
